// gencss generates internal/assets/static/highlight.css from chroma themes.
// Light theme (github) is the default; dark theme (github-dark) is scoped
// under the [data-theme="dark"] attribute selector.
//
// Usage: go run ./cmd/gencss
package main

import (
	"bufio"
	"bytes"
	"fmt"
	"log"
	"os"
	"strings"

	chromahtml "github.com/alecthomas/chroma/v2/formatters/html"
	"github.com/alecthomas/chroma/v2/styles"
)

const outPath = "internal/assets/static/highlight.css"

func main() {
	light, err := themeCSS("github")
	if err != nil {
		log.Fatalf("light theme: %v", err)
	}
	dark, err := themeCSS("dracula")
	if err != nil {
		log.Fatalf("dark theme: %v", err)
	}

	var buf bytes.Buffer
	fmt.Fprintf(&buf, "/* light: github — generated by cmd/gencss; do not edit */\n")
	buf.WriteString(light)
	// The github theme sets an explicit white background on .chroma, which
	// conflicts with PicoCSS's light-gray code background on non-highlighted
	// blocks. Override it with PicoCSS's own variable so both are consistent.
	fmt.Fprintf(&buf, "/* Match PicoCSS code background on highlighted blocks */\n")
	fmt.Fprintf(&buf, ".chroma { background-color: var(--pico-code-background-color); }\n")
	fmt.Fprintf(&buf, "\n/* dark: dracula — scoped to [data-theme=\"dark\"] */\n")
	buf.WriteString(prefixSelectors(dark, `[data-theme="dark"] `))

	if err := os.WriteFile(outPath, buf.Bytes(), 0o644); err != nil {
		log.Fatalf("write %s: %v", outPath, err)
	}
	fmt.Printf("wrote %s\n", outPath)
}

// themeCSS returns the chroma CSS for the named style using class-based output.
func themeCSS(name string) (string, error) {
	style := styles.Get(name)
	if style == nil {
		return "", fmt.Errorf("unknown style %q", name)
	}
	formatter := chromahtml.New(chromahtml.WithAllClasses(true))
	var buf bytes.Buffer
	if err := formatter.WriteCSS(&buf, style); err != nil {
		return "", err
	}
	return buf.String(), nil
}

// prefixSelectors prepends prefix to every non-blank line in src.
// Chroma CSS uses the format "/* TokenName */ .selector { rule }" on a single
// line. CSS treats comments as whitespace inside selectors, so prefixing the
// whole line produces a valid "[prefix] /* comment */ .selector { rule }".
func prefixSelectors(src, prefix string) string {
	var out strings.Builder
	scanner := bufio.NewScanner(strings.NewReader(src))
	for scanner.Scan() {
		line := scanner.Text()
		trimmed := strings.TrimSpace(line)
		if trimmed == "" {
			out.WriteString(line)
		} else {
			out.WriteString(prefix + trimmed)
		}
		out.WriteByte('\n')
	}
	return out.String()
}
